name: pony-lint

on:
  pull_request:
    paths:
      - '**/*.pony'

concurrency:
  group: pony-lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  pony-lint:
    name: Lint Pony source
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-standard-builder:release
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lint
        run: pony-lint
